In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')


In [2]:
df=sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [4]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
df.drop(["deck","embark_town","alive","adult_male","class","who"],axis=1,inplace=True)
df


,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True
887,1,1,female,19.0,0,0,30.0000,S,True
888,0,3,female,NaN,1,2,23.4500,S,False
889,1,1,male,26.0,0,0,30.0000,C,True


In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [7]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [8]:
df.dropna(subset="embarked",inplace=True)

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()


In [10]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


In [11]:
df['sex']=le.fit_transform(df['sex'])
df['embarked']=le.fit_transform(df['embarked'])

In [12]:
df=df.astype(int)


In [13]:
X=df.drop('survived',axis=1)
y=df['survived']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=32)


In [15]:
from sklearn.linear_model import LogisticRegression
logr=LogisticRegression()
logr.fit(X_train,y_train)

LogisticRegression()

In [16]:
y_pred=logr.predict(X_test)

In [17]:
from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report,
    precision_score,
    recall_score,
    f1_score,
)

In [18]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7921348314606742


In [19]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[102  18]
 [ 19  39]]


In [20]:
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

Precision: 0.6842105263157895


In [21]:
recall = recall_score(y_test, y_pred)
print("Recall:", recall)

Recall: 0.6724137931034483


In [22]:
f1 = f1_score(y_test, y_pred)
print("F1 Score:", f1)

F1 Score: 0.6782608695652174


In [23]:
print("\nClassification Report")
print(classification_report(y_test, y_pred))


Classification Report
              precision    recall  f1-score   support

           0       0.84      0.85      0.85       120
           1       0.68      0.67      0.68        58

    accuracy                           0.79       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.79      0.79      0.79       178



In [24]:
"KNN"
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()

In [25]:
X_train_scalar = scalar.fit_transform(X_train)
X_test_scalar=scalar.fit_transform(X_test)


In [26]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scalar,y_train)

KNeighborsClassifier()

In [27]:
y_pred_=knn_model.predict(X_test_scalar)

In [28]:
accuracy_score(y_pred_,y_test)

0.7921348314606742

In [29]:
confusion_matrix(y_test,y_pred_)

array([[101,  19],
       [ 18,  40]])

In [30]:
"NAVIES BAYES"
from sklearn.naive_bayes import GaussianNB
NB_model=GaussianNB()
"no need of the standard scalar  "

'no need of the standard scalar  '

In [31]:
NB_model.fit(X_train,y_train)

GaussianNB()

In [32]:
y_pred_NB=NB_model.predict(X_test)

In [33]:
accuracy_score(y_pred_NB,y_test)

0.7808988764044944

In [34]:
confusion_matrix(y_test,y_pred_NB)

array([[98, 22],
       [17, 41]])

In [35]:
print(classification_report(y_test, y_pred_NB))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       120
           1       0.65      0.71      0.68        58

    accuracy                           0.78       178
   macro avg       0.75      0.76      0.76       178
weighted avg       0.79      0.78      0.78       178



In [36]:
from sklearn.tree import DecisionTreeClassifier
model_DT=DecisionTreeClassifier(random_state=42)
"needed the feature scaling and we use X train scaled nd y train scaled "
model_DT.fit(X_train_scalar,y_train)

DecisionTreeClassifier(random_state=42)

In [37]:
y_pred_DT=model_DT.predict(X_test_scalar)

In [38]:
accuracy_score(y_pred_DT,y_test)

0.7528089887640449

In [39]:
"SVM"
from sklearn.svm  import SVC
model_SVM=SVC(kernel='rbf')
"it also use the featue scaling"
model_SVM.fit(X_train_scalar,y_train)


SVC()

In [40]:
y_pred_SVM=model_SVM.predict(X_test_scalar)

In [44]:
accuracy_score(y_test,y_pred_SVM)

0.8202247191011236

In [43]:
confusion_matrix(y_test,y_pred_SVM)

array([[108,  12],
       [ 20,  38]])

In [45]:
print(classification_report(y_test,y_pred_SVM))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87       120
           1       0.76      0.66      0.70        58

    accuracy                           0.82       178
   macro avg       0.80      0.78      0.79       178
weighted avg       0.82      0.82      0.82       178

